import TagsTech from "./tagsTech.js";

const technologies = [
    {
        id:1,
        url:TagsTech.HTML.url,
        name:TagsTech.HTML.name
    },
    {
        id:2,
        url:TagsTech.CSS.url,
        name:TagsTech.CSS.name
    },
    {
        id:3,
        url:TagsTech.JAVASCRIPT.url,
        name:TagsTech.JAVASCRIPT.name
    },
    {
        id:4,
        url:TagsTech.REACT.url,
        name:TagsTech.REACT.name
    },
    {
        id:5,
        url:TagsTech.ASTRO.url,
        name:TagsTech.ASTRO.name
    },
    {
        id:6,
        url:TagsTech.TAILWIND.url,
        name:TagsTech.TAILWIND.name
    },
    {
        id:7,
        url:TagsTech.BOOTSTRAP.url,
        name:TagsTech.BOOTSTRAP.name
    },
    {
        id:8,
        url:TagsTech.MYSQL.url,
        name:TagsTech.MYSQL.name
    },
    {
        id:9,
        url:TagsTech.JAVA.url,
        name:TagsTech.JAVA.name
    },
    {
        id:10,
        url:TagsTech.CSHARP.url,
        name:TagsTech.CSHARP.name
    },
    {
        id:11,
        url:TagsTech.NET.url,
        name:TagsTech.NET.name
    },
    {
        id:12,
        url:TagsTech.CMAS.url,
        name:TagsTech.CMAS.name
    }
]

export default technologies;